POST http://localhost:3001/api/completeactivity
Content-Type: application/json

{ 
    "activity": "Go for a 5km run",
    "accessibility": 0.1,
    "type": "individual", 
    "participants": 1,
    "price": 0,
    "username": "test2",
    "id": "6177ceef3bbb305b82fa8b9a",
    "score": 0,
    "completed": false
}

